### ISSUE TITLE
Runs triggered with `KERNEL_PUBLIC_KEY` empty fail

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity-os/plugin-sdk#36]
When no `KERNEL_PUBLIC_KEY` is supplied, the runs fail saying the given key is too short. My suspicion is that the default key is not used but `""` is used instead. See this run for reference: https://github.com/ubiquity-os-marketplace/daemon-pricing/actions/runs/12128570532/job/33815214041

SDKs will need to get updated across plugins as well.

**Comment by rndquu** [comment]
What is the difference between [context.env](https://github.com/ubiquity-os-marketplace/daemon-pricing/blob/74bd780f45d74ab567df8d35b5abb3ac708fa5bf/src/worker.ts#L19) and [env](https://github.com/ubiquity-os-marketplace/daemon-pricing/blob/74bd780f45d74ab567df8d35b5abb3ac708fa5bf/src/worker.ts#L28)? As far as I understand [env](https://github.com/ubiquity-os-marketplace/daemon-pricing/blob/74bd780f45d74ab567df8d35b5abb3ac708fa5bf/src/worker.ts#L28) contains variables from cloudflare worker and I'm not sure if it contains variables from github secrets.
